### PR TITLE
Update setttings.json

### PR DESCRIPTION
**Pull request by realahnet**
yes

### CODE REVIEW

**Comment by sinjs** [comment]
sytnxx error9!%!%&/&%!"6§!

**Comment by sinjs** [comment]
add komma

**Comment by realahnet** [comment]
no i m good

**Comment by sinjs** [comment]
but code brok

**Comment by realahnet** [comment]
how the fuck do i edit the pull request

**Review by sinjs — CHANGES_REQUESTED** [review]
bad

**Comment by sinjs** [comment]
yes

**Review by sinjs — APPROVED** [review]
amo

**Pull request merged**
